"""updated expiry and created dates in users

Revision ID: 631cf891bb1d
Revises: bbf0c57b930e
Create Date: 2024-03-24 10:20:39.923688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631cf891bb1d'
down_revision: Union[str, None] = 'bbf0c57b930e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ref_code_created_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'ref_code_created_at')
    # ### end Alembic commands ###
