"""updated expiry date field in users

Revision ID: bbf0c57b930e
Revises: 3d1d2f75f290
Create Date: 2024-03-24 10:16:26.617927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf0c57b930e'
down_revision: Union[str, None] = '3d1d2f75f290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ref_code_expiry_date', sa.DateTime(), nullable=True))
    op.drop_column('users', 'expiry_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expiry_date', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'ref_code_expiry_date')
    # ### end Alembic commands ###
